version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: games_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "6543:5432"
    volumes:
      - ./init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: